name: cicd to Snowflake with Terraform

on:
    pull_request:
      branches:
        - main
        - release/*
    push:
      branches:
        - main
        - release/*


jobs:
    security-scan-terraform-code:
        name: Security scan (terraform code)
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Run Bridgecrew 
            id: Bridgecrew
            uses: bridgecrewio/bridgecrew-action@master 
            env:
              PRISMA_API_URL: https://api.anz.prismacloud.io
            with:
              api-key: ${{ secrets.BC_API_KEY }}
              quiet: true
              soft_fail: true
    preview-dev:
        if: github.base_ref == 'main' && github.event_name == 'pull_request'
        needs: security-scan-terraform-code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-southeast-2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              id: terraform_init
              run: terraform -chdir=./dev init

            - name: Terraform Format
              id: fmt
              run: terraform -chdir=./dev fmt -recursive -check

            - name: Terraform Validate
              id: validate
              run: terraform -chdir=./dev validate -no-color

            - name: Terraform Plan
              id: plan
              run: terraform -chdir=./staging plan 
              env:
                TF_VAR_snowflake_private_key: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

    deploy-dev:
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        needs: security-scan-terraform-code
        runs-on: ubuntu-latest
        environment: 'dev'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-southeast-2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              id: terraform_init
              run: terraform -chdir=./dev init

            - name: Terraform Format
              id: fmt
              run: terraform -chdir=./dev fmt -recursive -check

            - name: Terraform Validate
              id: validate
              run: terraform -chdir=./dev validate -no-color

            - name: Terraform Plan
              id: plan
              run: terraform -chdir=./staging plan 
              env:
                TF_VAR_snowflake_private_key: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

            - name: Terraform Apply
              id: apply
              run: terraform -chdir=./staging apply -auto-approve
              env:
                TF_VAR_snowflake_private_key: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

    preview-prod:
        if: startsWith(github.ref, 'refs/heads/release/')
        needs: security-scan-terraform-code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-southeast-2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              id: terraform_init
              run: terraform -chdir=./dev init

            - name: Terraform Format
              id: fmt
              run: terraform -chdir=./dev fmt -recursive -check

            - name: Terraform Validate
              id: validate
              run: terraform -chdir=./dev validate -no-color

            - name: Terraform Plan
              id: plan
              run: terraform -chdir=./staging plan 
              env:
                TF_VAR_snowflake_private_key: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

    deploy-prod:
        if: startsWith(github.ref, 'refs/heads/release/') && github.event_name == 'push'
        needs: preview-prod
        runs-on: ubuntu-latest
        environment: 'prod'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-southeast-2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              id: terraform_init
              run: terraform -chdir=./dev init

            - name: Terraform Format
              id: fmt
              run: terraform -chdir=./dev fmt -recursive -check

            - name: Terraform Validate
              id: validate
              run: terraform -chdir=./dev validate -no-color

            - name: Terraform Plan
              id: plan
              run: terraform -chdir=./staging plan 
              env:
                TF_VAR_snowflake_private_key: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

            - name: Terraform Apply
              id: apply
              run: terraform -chdir=./staging apply -auto-approve
              env:
                TF_VAR_snowflake_private_key: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}